export enum RoutesPath {
  SERVER = 'YOU_IP',
  USER_LOGIN = 'api/v1/users/sign_in',
  COMPANY_LOGIN = 'api/v1/users/sign_in',
  COMPANY_REGISTER = 'api/v1/users/create',
  USER_REGISTER = 'api/v1/users/create',
  USER_LOGGIN_SUCCESS = '/user/dashboard',
  COMPANY_LOGGIN_SUCCESS = '/company/dashboard',
  LIST_JOBS = '/api/v1/jobs/list_jobs',
  CREATED_JOB = 'api/v1/jobs/create',
  APPLY = '/api/v1/matchings/apply',
  AUTH = 'api/v1/authenticate/login',
  AUTH_FIND_JOB_BY_ID = '/api/v1/authenticate/find_by_job_id',
  USER_DASHBOARD = '/api/v1/authenticate/user_dashboard',
  DASHBOARD = '/api/v1/authenticate/dashboard',
  DASHBOARD_OPPORTUNITY = '/api/v1/authenticate/dashboard/opportunity',
  USER_UPDATE = '/api/v1/users/update',
}
